shortener/urls.py
from django.conf.urls import patterns, include, url

from shortener import views

urlpatterns = patterns('',
    url(r'^$', views.home, name='home'),
    url(r'^create/?$', views.create, name='create'),
    url(r'^(?P<short_code>\w+)/$', views.show, name='show'),
    url(r'^(?P<short_code>\w+)/info/$', views.info, name='info'),
)

shorty/urls.py
from django.contrib import admin
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'shorty.views.home', name='home'),
    # url(r'^shorty/', include('shorty.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('shortener.urls', namespace='shortener')),
)

shortener/models.py
import uuid
import re
from django.db import models
from django.db.models import Count
from django.db import connection

class ShortURL(models.Model):
    SPAM_BLACKLIST = ['spammer.net']

    url = models.URLField(
        max_length=1000,
        verbose_name='URL to shorten',
    )
    short_code = models.CharField(
        max_length=30,
        unique=True,
        blank=True,
    )

    def __unicode__(self):
        return self.short_code

    def save(self, *args, **kwargs):
        if not self.pk:
            # Has never been saved
            if self.short_code == '':
                self.short_code = choose_short_code()
        super(ShortURL, self).save(*args, **kwargs)

    def visits_by_browser(self):
        return self.visit_set.all().values('browser').annotate(count=Count('browser'))

    def visits_by_hour(self):
        cursor = connection.cursor()
        sql = """
        select EXTRACT(HOUR from visited_at) AS hour, count(id) AS count
        from shortener_visit
        where short_url_id = {0}
        group by hour
        """.format(self.id)
        cursor.execute(sql)
        return dictfetchall(cursor)

    def is_blacklisted_site(self):
        return any([
            site in self.url for site in self.SPAM_BLACKLIST
        ])
    is_blacklisted_site.boolean = True
    is_blacklisted_site.short_description = 'Blacklisted site?'

class Visit(models.Model):
    short_url = models.ForeignKey(ShortURL)
    visited_at = models.DateTimeField()
    os = models.CharField(max_length=100)
    browser = models.CharField(max_length=100)
    version = models.CharField(max_length=100)

    def __unicode__(self):
        return "{0} {1} {2} at {3}".format(self.os, self.browser, self.version, self.visited_at)

def generate_short_code():
    return str(uuid.uuid1())[0:7]

def choose_short_code():
    code = generate_short_code()
    while ShortURL.objects.filter(short_code=code).exists():
        code = generate_short_code()
    return code

def dictfetchall(cursor):
    "Returns all rows from a cursor as a dict"
    desc = cursor.description
    return [
        dict(zip([col[0] for col in desc], row))
        for row in cursor.fetchall()
    ]

shortener/forms.py
from django.forms import ModelForm

from shortener.models import ShortURL

class CreateShortURLForm(ModelForm):
    class Meta:
        model = ShortURL

shortener/views.py
import datetime
from itertools import groupby
from django.http import HttpResponseRedirect
from django.views.decorators.http import require_POST, require_safe
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse

from shortener import forms
from shortener.models import ShortURL, Visit
from shortener.helpers import parse_browser

def home(request):
    form = forms.CreateShortURLForm()
    return render(request, 'shortener/home.html', {'form': form})

@require_POST
def create(request):
    form = forms.CreateShortURLForm(request.POST)

    if form.is_valid():
        ShortURL.objects.create(**form.cleaned_data)
        return HttpResponseRedirect(reverse('shortener:home'))
    else:
        return render(request, 'shortener/home.html', {'form': form})

@require_safe
def show(request, short_code):
    short_url = get_object_or_404(ShortURL, short_code=short_code)
    os, browser, version = parse_browser(request.META['HTTP_USER_AGENT'])
    # failing it should be ok
    Visit.objects.create(
        short_url=short_url,
        os = os, browser = browser, version = version,
        visited_at=datetime.datetime.utcnow(),
    )
    return HttpResponseRedirect(short_url.url)

@require_safe
def info(request, short_code):
    short_url = get_object_or_404(ShortURL, short_code=short_code)
    visits_by_browser = short_url.visits_by_browser()
    visits_by_hour = short_url.visits_by_hour()
    return render(request, 'shortener/info.html', {
        'short_url': short_url,
        'visits_by_browser': visits_by_browser,
        'visits_by_hour': visits_by_hour,
    })

shortener/templates/shortener/base.html
<!DOCTYPE html>
{% load bootstrap_toolkit %}
{% load url from future %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Shorten URLs!</title>
    <meta name="description" content="the best url shortener">
    <meta name="author" content="Arnab Deka">
    {% bootstrap_stylesheet_tag %}
    {% bootstrap_stylesheet_tag "responsive" %}
    <style type="text/css">
        body {
            padding-top: 60px;
        }
    </style>
    <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
    {% bootstrap_javascript_tag %}
    {% block extra_head %}{% endblock %}
</head>

<body>

<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="{% url 'shortener:home' %}">shorty</a>
            <ul class="nav">
                <li><a href="{% url 'shortener:home' %}" class="">Home</a></li>
                <li><a href="{% url 'shortener:home' %}" class="">About</a></li>
            </ul>
        </div>
    </div>
</div>

<div class="container">

    {% bootstrap_messages %}

    {% block content %}Empty page{% endblock %}

    <p><hr></p>

    <footer class="row">
        <div class="span6">
            <p>source in <a href="https://github.com/arnab/compricin_py">github</a></p>
        </div>
        <div class="span6" style="text-align:right">
            <p>
                &copy; <a href="http://twitter.com/arnab_deka">Arnab Deka</a> 2013
            </p>
        </div>
    </footer>

</div> <!-- container -->

</body>
</html>

shortener/templates/shortener/home.html
{% extends "shortener/base.html" %}
{% load bootstrap_toolkit %}
{% block content %}

<form action='{% url 'shortener:create' %}' method='post'>
    {% csrf_token %}
    {{ form.non_field_errors }}

    {{ form|as_bootstrap }}
    <input type="submit" class="text btn btn-primary" value="Create">
</form>

{% endblock %}

shortener/templates/shortener/info.html
{% extends "shortener/base.html" %}
{% load bootstrap_toolkit %}
{% block content %}

<h1>shorty/{{ short_url.short_code }}</h1>
<h4>target: {{ short_url.url }}</h4>

<h2>Visits by browser</h2>
<table class='table table-striped table-bordered table-hover'>
{% for data in visits_by_browser %}
<tr>
    <td>{{ data.browser }}</td>
    <td>{{ data.count }}</td>
</tr>
{% endfor %}
</table>

<h2>Visits by hour</h2>
<table class='table table-striped table-bordered table-hover'>
{% for data in visits_by_hour %}
<tr>
    <td>{{ data.hour }}</td>
    <td>{{ data.count }}</td>
</tr>
{% endfor %}
</table>

{% endblock %}